# Generated by Django 4.1.7 on 2023-04-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
